FROM node:14.17-alpine

RUN apk add --no-cache jq
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY ../.eslintignore .
COPY ../.eslintrc.js .
COPY ../tsconfig.base.json .
COPY ../tsconfig.eslint.json .
COPY ../package.json .
COPY ../yarn.lock .
COPY package.json frontend/package.json
COPY yarn.lock frontend/yarn.lock

RUN yarn install

WORKDIR /home/node/app/frontend

COPY . .

# Not sure why it doesn't work without another round of install
CMD yarn install && yarn start
