// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.6
// source: code2gather.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionDifficulty int32

const (
	QuestionDifficulty_UNKNOWN QuestionDifficulty = 0
	QuestionDifficulty_EASY    QuestionDifficulty = 1
	QuestionDifficulty_MEDIUM  QuestionDifficulty = 2
	QuestionDifficulty_HARD    QuestionDifficulty = 3
)

// Enum value maps for QuestionDifficulty.
var (
	QuestionDifficulty_name = map[int32]string{
		0: "UNKNOWN",
		1: "EASY",
		2: "MEDIUM",
		3: "HARD",
	}
	QuestionDifficulty_value = map[string]int32{
		"UNKNOWN": 0,
		"EASY":    1,
		"MEDIUM":  2,
		"HARD":    3,
	}
)

func (x QuestionDifficulty) Enum() *QuestionDifficulty {
	p := new(QuestionDifficulty)
	*p = x
	return p
}

func (x QuestionDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_code2gather_proto_enumTypes[0].Descriptor()
}

func (QuestionDifficulty) Type() protoreflect.EnumType {
	return &file_code2gather_proto_enumTypes[0]
}

func (x QuestionDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionDifficulty.Descriptor instead.
func (QuestionDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{0}
}

type QuestionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text       string             `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Difficulty QuestionDifficulty `protobuf:"varint,4,opt,name=difficulty,proto3,enum=code2gather.QuestionDifficulty" json:"difficulty,omitempty"`
	Hints      string             `protobuf:"bytes,5,opt,name=hints,proto3" json:"hints,omitempty"`
}

func (x *QuestionMessage) Reset() {
	*x = QuestionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionMessage) ProtoMessage() {}

func (x *QuestionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionMessage.ProtoReflect.Descriptor instead.
func (*QuestionMessage) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuestionMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuestionMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QuestionMessage) GetDifficulty() QuestionDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return QuestionDifficulty_UNKNOWN
}

func (x *QuestionMessage) GetHints() string {
	if x != nil {
		return x.Hints
	}
	return ""
}

type RoomMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid1 string `protobuf:"bytes,2,opt,name=uid1,proto3" json:"uid1,omitempty"`
	Uid2 string `protobuf:"bytes,3,opt,name=uid2,proto3" json:"uid2,omitempty"`
	Qid1 string `protobuf:"bytes,4,opt,name=qid1,proto3" json:"qid1,omitempty"`
	Qid2 string `protobuf:"bytes,5,opt,name=qid2,proto3" json:"qid2,omitempty"`
}

func (x *RoomMessage) Reset() {
	*x = RoomMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMessage) ProtoMessage() {}

func (x *RoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMessage.ProtoReflect.Descriptor instead.
func (*RoomMessage) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{1}
}

func (x *RoomMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomMessage) GetUid1() string {
	if x != nil {
		return x.Uid1
	}
	return ""
}

func (x *RoomMessage) GetUid2() string {
	if x != nil {
		return x.Uid2
	}
	return ""
}

func (x *RoomMessage) GetQid1() string {
	if x != nil {
		return x.Qid1
	}
	return ""
}

func (x *RoomMessage) GetQid2() string {
	if x != nil {
		return x.Qid2
	}
	return ""
}

// HTTP POST request (Pairing -> Room)
type CreateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid1       string             `protobuf:"bytes,1,opt,name=uid1,proto3" json:"uid1,omitempty"`
	Uid2       string             `protobuf:"bytes,2,opt,name=uid2,proto3" json:"uid2,omitempty"`
	Difficulty QuestionDifficulty `protobuf:"varint,3,opt,name=difficulty,proto3,enum=code2gather.QuestionDifficulty" json:"difficulty,omitempty"`
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomRequest) GetUid1() string {
	if x != nil {
		return x.Uid1
	}
	return ""
}

func (x *CreateRoomRequest) GetUid2() string {
	if x != nil {
		return x.Uid2
	}
	return ""
}

func (x *CreateRoomRequest) GetDifficulty() QuestionDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return QuestionDifficulty_UNKNOWN
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_code2gather_proto protoreflect.FileDescriptor

var file_code2gather_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x22, 0xa2, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x3f,
	0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75,
	0x6c, 0x74, 0x79, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x68, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x68, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x6d, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x31, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x32, 0x12, 0x12, 0x0a, 0x04,
	0x71, 0x69, 0x64, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x71, 0x69, 0x64, 0x31,
	0x12, 0x12, 0x0a, 0x04, 0x71, 0x69, 0x64, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x71, 0x69, 0x64, 0x32, 0x22, 0x7c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x31, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x69, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64,
	0x32, 0x12, 0x3f, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x66, 0x66,
	0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c,
	0x74, 0x79, 0x22, 0x2d, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x2a, 0x41, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x66,
	0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x41, 0x53, 0x59, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x41,
	0x52, 0x44, 0x10, 0x03, 0x42, 0x09, 0x5a, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_code2gather_proto_rawDescOnce sync.Once
	file_code2gather_proto_rawDescData = file_code2gather_proto_rawDesc
)

func file_code2gather_proto_rawDescGZIP() []byte {
	file_code2gather_proto_rawDescOnce.Do(func() {
		file_code2gather_proto_rawDescData = protoimpl.X.CompressGZIP(file_code2gather_proto_rawDescData)
	})
	return file_code2gather_proto_rawDescData
}

var file_code2gather_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_code2gather_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_code2gather_proto_goTypes = []interface{}{
	(QuestionDifficulty)(0),    // 0: code2gather.QuestionDifficulty
	(*QuestionMessage)(nil),    // 1: code2gather.QuestionMessage
	(*RoomMessage)(nil),        // 2: code2gather.RoomMessage
	(*CreateRoomRequest)(nil),  // 3: code2gather.CreateRoomRequest
	(*CreateRoomResponse)(nil), // 4: code2gather.CreateRoomResponse
}
var file_code2gather_proto_depIdxs = []int32{
	0, // 0: code2gather.QuestionMessage.difficulty:type_name -> code2gather.QuestionDifficulty
	0, // 1: code2gather.CreateRoomRequest.difficulty:type_name -> code2gather.QuestionDifficulty
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_code2gather_proto_init() }
func file_code2gather_proto_init() {
	if File_code2gather_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_code2gather_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_code2gather_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_code2gather_proto_goTypes,
		DependencyIndexes: file_code2gather_proto_depIdxs,
		EnumInfos:         file_code2gather_proto_enumTypes,
		MessageInfos:      file_code2gather_proto_msgTypes,
	}.Build()
	File_code2gather_proto = out.File
	file_code2gather_proto_rawDesc = nil
	file_code2gather_proto_goTypes = nil
	file_code2gather_proto_depIdxs = nil
}
