// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.6
// source: code2gather.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionDifficulty int32

const (
	QuestionDifficulty_UNKNOWN_DIFFICULTY QuestionDifficulty = 0
	QuestionDifficulty_EASY               QuestionDifficulty = 1
	QuestionDifficulty_MEDIUM             QuestionDifficulty = 2
	QuestionDifficulty_HARD               QuestionDifficulty = 3
)

// Enum value maps for QuestionDifficulty.
var (
	QuestionDifficulty_name = map[int32]string{
		0: "UNKNOWN_DIFFICULTY",
		1: "EASY",
		2: "MEDIUM",
		3: "HARD",
	}
	QuestionDifficulty_value = map[string]int32{
		"UNKNOWN_DIFFICULTY": 0,
		"EASY":               1,
		"MEDIUM":             2,
		"HARD":               3,
	}
)

func (x QuestionDifficulty) Enum() *QuestionDifficulty {
	p := new(QuestionDifficulty)
	*p = x
	return p
}

func (x QuestionDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_code2gather_proto_enumTypes[0].Descriptor()
}

func (QuestionDifficulty) Type() protoreflect.EnumType {
	return &file_code2gather_proto_enumTypes[0]
}

func (x QuestionDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionDifficulty.Descriptor instead.
func (QuestionDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{0}
}

type Language int32

const (
	Language_UNKNOWN_LANGUGAE Language = 0
	Language_PYTHON           Language = 1
	Language_JAVA             Language = 2
	Language_JAVASCRIPT       Language = 3
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "UNKNOWN_LANGUGAE",
		1: "PYTHON",
		2: "JAVA",
		3: "JAVASCRIPT",
	}
	Language_value = map[string]int32{
		"UNKNOWN_LANGUGAE": 0,
		"PYTHON":           1,
		"JAVA":             2,
		"JAVASCRIPT":       3,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_code2gather_proto_enumTypes[1].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_code2gather_proto_enumTypes[1]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{1}
}

type ErrorCode int32

const (
	// success
	ErrorCode_NO_ERROR ErrorCode = 0
	// system error (unexpected error)
	ErrorCode_UNKNOWN_ERROR ErrorCode = -1
	// client/business error (expected error)
	ErrorCode_MESSAGE_CODING_ERROR ErrorCode = 1
	ErrorCode_UNAUTHORIZED_USER    ErrorCode = 2
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "NO_ERROR",
		-1: "UNKNOWN_ERROR",
		1:  "MESSAGE_CODING_ERROR",
		2:  "UNAUTHORIZED_USER",
	}
	ErrorCode_value = map[string]int32{
		"NO_ERROR":             0,
		"UNKNOWN_ERROR":        -1,
		"MESSAGE_CODING_ERROR": 1,
		"UNAUTHORIZED_USER":    2,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_code2gather_proto_enumTypes[2].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_code2gather_proto_enumTypes[2]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{2}
}

type QuestionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text       string             `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Difficulty QuestionDifficulty `protobuf:"varint,4,opt,name=difficulty,proto3,enum=code2gather.QuestionDifficulty" json:"difficulty,omitempty"`
	Hints      string             `protobuf:"bytes,5,opt,name=hints,proto3" json:"hints,omitempty"`
}

func (x *QuestionMessage) Reset() {
	*x = QuestionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionMessage) ProtoMessage() {}

func (x *QuestionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionMessage.ProtoReflect.Descriptor instead.
func (*QuestionMessage) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuestionMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuestionMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QuestionMessage) GetDifficulty() QuestionDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return QuestionDifficulty_UNKNOWN_DIFFICULTY
}

func (x *QuestionMessage) GetHints() string {
	if x != nil {
		return x.Hints
	}
	return ""
}

type RoomMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid1 string `protobuf:"bytes,2,opt,name=uid1,proto3" json:"uid1,omitempty"`
	Uid2 string `protobuf:"bytes,3,opt,name=uid2,proto3" json:"uid2,omitempty"`
	Qid1 string `protobuf:"bytes,4,opt,name=qid1,proto3" json:"qid1,omitempty"`
	Qid2 string `protobuf:"bytes,5,opt,name=qid2,proto3" json:"qid2,omitempty"`
}

func (x *RoomMessage) Reset() {
	*x = RoomMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMessage) ProtoMessage() {}

func (x *RoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMessage.ProtoReflect.Descriptor instead.
func (*RoomMessage) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{1}
}

func (x *RoomMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomMessage) GetUid1() string {
	if x != nil {
		return x.Uid1
	}
	return ""
}

func (x *RoomMessage) GetUid2() string {
	if x != nil {
		return x.Uid2
	}
	return ""
}

func (x *RoomMessage) GetQid1() string {
	if x != nil {
		return x.Qid1
	}
	return ""
}

func (x *RoomMessage) GetQid2() string {
	if x != nil {
		return x.Qid2
	}
	return ""
}

// HTTP POST request (Pairing -> Room)
type CreateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid1       string             `protobuf:"bytes,1,opt,name=uid1,proto3" json:"uid1,omitempty"`
	Uid2       string             `protobuf:"bytes,2,opt,name=uid2,proto3" json:"uid2,omitempty"`
	Difficulty QuestionDifficulty `protobuf:"varint,3,opt,name=difficulty,proto3,enum=code2gather.QuestionDifficulty" json:"difficulty,omitempty"`
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomRequest) GetUid1() string {
	if x != nil {
		return x.Uid1
	}
	return ""
}

func (x *CreateRoomRequest) GetUid2() string {
	if x != nil {
		return x.Uid2
	}
	return ""
}

func (x *CreateRoomRequest) GetDifficulty() QuestionDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return QuestionDifficulty_UNKNOWN_DIFFICULTY
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// HTTP POST request /meeting (Room -> History)
type CreateMeetingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterviewerId         string             `protobuf:"bytes,1,opt,name=interviewer_id,json=interviewerId,proto3" json:"interviewer_id,omitempty"`
	IntervieweeId         string             `protobuf:"bytes,2,opt,name=interviewee_id,json=intervieweeId,proto3" json:"interviewee_id,omitempty"`
	Duration              int32              `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	QuestionId            string             `protobuf:"bytes,4,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Difficulty            QuestionDifficulty `protobuf:"varint,5,opt,name=difficulty,proto3,enum=code2gather.QuestionDifficulty" json:"difficulty,omitempty"`
	Language              Language           `protobuf:"varint,6,opt,name=language,proto3,enum=code2gather.Language" json:"language,omitempty"`
	CodeWritten           string             `protobuf:"bytes,7,opt,name=code_written,json=codeWritten,proto3" json:"code_written,omitempty"`
	IsSolved              bool               `protobuf:"varint,8,opt,name=is_solved,json=isSolved,proto3" json:"is_solved,omitempty"`
	FeedbackToInterviewee string             `protobuf:"bytes,9,opt,name=feedback_to_interviewee,json=feedbackToInterviewee,proto3" json:"feedback_to_interviewee,omitempty"`
}

func (x *CreateMeetingRequest) Reset() {
	*x = CreateMeetingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingRequest) ProtoMessage() {}

func (x *CreateMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingRequest.ProtoReflect.Descriptor instead.
func (*CreateMeetingRequest) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMeetingRequest) GetInterviewerId() string {
	if x != nil {
		return x.InterviewerId
	}
	return ""
}

func (x *CreateMeetingRequest) GetIntervieweeId() string {
	if x != nil {
		return x.IntervieweeId
	}
	return ""
}

func (x *CreateMeetingRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateMeetingRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *CreateMeetingRequest) GetDifficulty() QuestionDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return QuestionDifficulty_UNKNOWN_DIFFICULTY
}

func (x *CreateMeetingRequest) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_UNKNOWN_LANGUGAE
}

func (x *CreateMeetingRequest) GetCodeWritten() string {
	if x != nil {
		return x.CodeWritten
	}
	return ""
}

func (x *CreateMeetingRequest) GetIsSolved() bool {
	if x != nil {
		return x.IsSolved
	}
	return false
}

func (x *CreateMeetingRequest) GetFeedbackToInterviewee() string {
	if x != nil {
		return x.FeedbackToInterviewee
	}
	return ""
}

// HTTP POST request /rating (Room -> History)
type CreateRatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rating       float32 `protobuf:"fixed32,1,opt,name=rating,proto3" json:"rating,omitempty"`
	RatingUserId string  `protobuf:"bytes,2,opt,name=rating_user_id,json=ratingUserId,proto3" json:"rating_user_id,omitempty"`
	RatedUserId  string  `protobuf:"bytes,3,opt,name=rated_user_id,json=ratedUserId,proto3" json:"rated_user_id,omitempty"`
	RoomId       string  `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *CreateRatingRequest) Reset() {
	*x = CreateRatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingRequest) ProtoMessage() {}

func (x *CreateRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingRequest.ProtoReflect.Descriptor instead.
func (*CreateRatingRequest) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRatingRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateRatingRequest) GetRatingUserId() string {
	if x != nil {
		return x.RatingUserId
	}
	return ""
}

func (x *CreateRatingRequest) GetRatedUserId() string {
	if x != nil {
		return x.RatedUserId
	}
	return ""
}

func (x *CreateRatingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//	*ClientRequest_JoinRoomRequest
	//	*ClientRequest_ExecuteCodeRequest
	//	*ClientRequest_CompleteQuestionRequest
	//	*ClientRequest_SubmitRatingRequest
	Request isClientRequest_Request `protobuf_oneof:"request"`
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{7}
}

func (m *ClientRequest) GetRequest() isClientRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *ClientRequest) GetJoinRoomRequest() *JoinRoomRequest {
	if x, ok := x.GetRequest().(*ClientRequest_JoinRoomRequest); ok {
		return x.JoinRoomRequest
	}
	return nil
}

func (x *ClientRequest) GetExecuteCodeRequest() *ExecuteCodeRequest {
	if x, ok := x.GetRequest().(*ClientRequest_ExecuteCodeRequest); ok {
		return x.ExecuteCodeRequest
	}
	return nil
}

func (x *ClientRequest) GetCompleteQuestionRequest() *CompleteQuestionRequest {
	if x, ok := x.GetRequest().(*ClientRequest_CompleteQuestionRequest); ok {
		return x.CompleteQuestionRequest
	}
	return nil
}

func (x *ClientRequest) GetSubmitRatingRequest() *SubmitRatingRequest {
	if x, ok := x.GetRequest().(*ClientRequest_SubmitRatingRequest); ok {
		return x.SubmitRatingRequest
	}
	return nil
}

type isClientRequest_Request interface {
	isClientRequest_Request()
}

type ClientRequest_JoinRoomRequest struct {
	JoinRoomRequest *JoinRoomRequest `protobuf:"bytes,1,opt,name=join_room_request,json=joinRoomRequest,proto3,oneof"`
}

type ClientRequest_ExecuteCodeRequest struct {
	ExecuteCodeRequest *ExecuteCodeRequest `protobuf:"bytes,2,opt,name=execute_code_request,json=executeCodeRequest,proto3,oneof"`
}

type ClientRequest_CompleteQuestionRequest struct {
	CompleteQuestionRequest *CompleteQuestionRequest `protobuf:"bytes,3,opt,name=complete_question_request,json=completeQuestionRequest,proto3,oneof"`
}

type ClientRequest_SubmitRatingRequest struct {
	SubmitRatingRequest *SubmitRatingRequest `protobuf:"bytes,4,opt,name=submit_rating_request,json=submitRatingRequest,proto3,oneof"`
}

func (*ClientRequest_JoinRoomRequest) isClientRequest_Request() {}

func (*ClientRequest_ExecuteCodeRequest) isClientRequest_Request() {}

func (*ClientRequest_CompleteQuestionRequest) isClientRequest_Request() {}

func (*ClientRequest_SubmitRatingRequest) isClientRequest_Request() {}

type JoinRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode     int32            `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	InterviewerId string           `protobuf:"bytes,2,opt,name=interviewer_id,json=interviewerId,proto3" json:"interviewer_id,omitempty"`
	Question      *QuestionMessage `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{9}
}

func (x *JoinRoomResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *JoinRoomResponse) GetInterviewerId() string {
	if x != nil {
		return x.InterviewerId
	}
	return ""
}

func (x *JoinRoomResponse) GetQuestion() *QuestionMessage {
	if x != nil {
		return x.Question
	}
	return nil
}

type ExecuteCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Code     string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Language Language `protobuf:"varint,3,opt,name=language,proto3,enum=code2gather.Language" json:"language,omitempty"`
}

func (x *ExecuteCodeRequest) Reset() {
	*x = ExecuteCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCodeRequest) ProtoMessage() {}

func (x *ExecuteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCodeRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCodeRequest) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteCodeRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ExecuteCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteCodeRequest) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_UNKNOWN_LANGUGAE
}

type ExecuteCodeBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExecutingUid string `protobuf:"bytes,1,opt,name=executing_uid,json=executingUid,proto3" json:"executing_uid,omitempty"`
}

func (x *ExecuteCodeBroadcast) Reset() {
	*x = ExecuteCodeBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteCodeBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCodeBroadcast) ProtoMessage() {}

func (x *ExecuteCodeBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCodeBroadcast.ProtoReflect.Descriptor instead.
func (*ExecuteCodeBroadcast) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteCodeBroadcast) GetExecutingUid() string {
	if x != nil {
		return x.ExecutingUid
	}
	return ""
}

type ExecuteCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Output    string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *ExecuteCodeResponse) Reset() {
	*x = ExecuteCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCodeResponse) ProtoMessage() {}

func (x *ExecuteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCodeResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCodeResponse) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteCodeResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ExecuteCodeResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type DisconnectBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DisconnectedUid string `protobuf:"bytes,1,opt,name=disconnected_uid,json=disconnectedUid,proto3" json:"disconnected_uid,omitempty"`
}

func (x *DisconnectBroadcast) Reset() {
	*x = DisconnectBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisconnectBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectBroadcast) ProtoMessage() {}

func (x *DisconnectBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectBroadcast.ProtoReflect.Descriptor instead.
func (*DisconnectBroadcast) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{13}
}

func (x *DisconnectBroadcast) GetDisconnectedUid() string {
	if x != nil {
		return x.DisconnectedUid
	}
	return ""
}

type CompleteQuestionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId                string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	IsSolved              bool     `protobuf:"varint,2,opt,name=is_solved,json=isSolved,proto3" json:"is_solved,omitempty"`
	FeedbackToInterviewee string   `protobuf:"bytes,3,opt,name=feedback_to_interviewee,json=feedbackToInterviewee,proto3" json:"feedback_to_interviewee,omitempty"`
	CodeWritten           string   `protobuf:"bytes,4,opt,name=code_written,json=codeWritten,proto3" json:"code_written,omitempty"`
	Language              Language `protobuf:"varint,5,opt,name=language,proto3,enum=code2gather.Language" json:"language,omitempty"`
}

func (x *CompleteQuestionRequest) Reset() {
	*x = CompleteQuestionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteQuestionRequest) ProtoMessage() {}

func (x *CompleteQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteQuestionRequest.ProtoReflect.Descriptor instead.
func (*CompleteQuestionRequest) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{14}
}

func (x *CompleteQuestionRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CompleteQuestionRequest) GetIsSolved() bool {
	if x != nil {
		return x.IsSolved
	}
	return false
}

func (x *CompleteQuestionRequest) GetFeedbackToInterviewee() string {
	if x != nil {
		return x.FeedbackToInterviewee
	}
	return ""
}

func (x *CompleteQuestionRequest) GetCodeWritten() string {
	if x != nil {
		return x.CodeWritten
	}
	return ""
}

func (x *CompleteQuestionRequest) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_UNKNOWN_LANGUGAE
}

type CompleteQuestionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode     int32            `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	InterviewerId string           `protobuf:"bytes,2,opt,name=interviewer_id,json=interviewerId,proto3" json:"interviewer_id,omitempty"`
	NextQuestion  *QuestionMessage `protobuf:"bytes,3,opt,name=next_question,json=nextQuestion,proto3" json:"next_question,omitempty"`
}

func (x *CompleteQuestionResponse) Reset() {
	*x = CompleteQuestionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteQuestionResponse) ProtoMessage() {}

func (x *CompleteQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteQuestionResponse.ProtoReflect.Descriptor instead.
func (*CompleteQuestionResponse) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{15}
}

func (x *CompleteQuestionResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CompleteQuestionResponse) GetInterviewerId() string {
	if x != nil {
		return x.InterviewerId
	}
	return ""
}

func (x *CompleteQuestionResponse) GetNextQuestion() *QuestionMessage {
	if x != nil {
		return x.NextQuestion
	}
	return nil
}

type SubmitRatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string  `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Rating float32 `protobuf:"fixed32,2,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *SubmitRatingRequest) Reset() {
	*x = SubmitRatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRatingRequest) ProtoMessage() {}

func (x *SubmitRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRatingRequest.ProtoReflect.Descriptor instead.
func (*SubmitRatingRequest) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitRatingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SubmitRatingRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type SubmitRatingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
}

func (x *SubmitRatingResponse) Reset() {
	*x = SubmitRatingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code2gather_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRatingResponse) ProtoMessage() {}

func (x *SubmitRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code2gather_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRatingResponse.ProtoReflect.Descriptor instead.
func (*SubmitRatingResponse) Descriptor() ([]byte, []int) {
	return file_code2gather_proto_rawDescGZIP(), []int{17}
}

func (x *SubmitRatingResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

var File_code2gather_proto protoreflect.FileDescriptor

var file_code2gather_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x22, 0xa2, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x3f,
	0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75,
	0x6c, 0x74, 0x79, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x68, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x68, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x6d, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x31, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x32, 0x12, 0x12, 0x0a, 0x04,
	0x71, 0x69, 0x64, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x71, 0x69, 0x64, 0x31,
	0x12, 0x12, 0x0a, 0x04, 0x71, 0x69, 0x64, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x71, 0x69, 0x64, 0x32, 0x22, 0x7c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x31, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x69, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64,
	0x32, 0x12, 0x3f, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x66, 0x66,
	0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c,
	0x74, 0x79, 0x22, 0x2d, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x22, 0x8d, 0x03, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x65, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x69, 0x65, 0x77, 0x65, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75,
	0x6c, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x64, 0x65,
	0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66,
	0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x32,
	0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x52,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x64,
	0x65, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x64, 0x65, 0x57, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x73, 0x5f, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x17, 0x66, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x6f, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69,
	0x65, 0x77, 0x65, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x66, 0x65, 0x65, 0x64,
	0x62, 0x61, 0x63, 0x6b, 0x54, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x65,
	0x65, 0x22, 0x90, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x12, 0x24, 0x0a, 0x0e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xf7,
	0x02, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x4a, 0x0a, 0x11, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f,
	0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x6a, 0x6f, 0x69,
	0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x14,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x64,
	0x65, 0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x12, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x62, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x17, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x15, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x5f,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x13, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x22, 0x92, 0x01, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x38, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x74, 0x0a, 0x12, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x31, 0x0a, 0x08,
	0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22,
	0x3b, 0x0a, 0x14, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x55, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x13,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x40, 0x0a, 0x13, 0x44, 0x69,
	0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x55, 0x69, 0x64, 0x22, 0xdd, 0x01, 0x0a,
	0x17, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x12, 0x36,
	0x0a, 0x17, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x6f, 0x5f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x15, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x69, 0x65, 0x77, 0x65, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x77,
	0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x64, 0x65, 0x57, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x12, 0x31, 0x0a, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x63, 0x6f,
	0x64, 0x65, 0x32, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0xa3, 0x01, 0x0a,
	0x18, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x41, 0x0a, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x67, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x0c, 0x6e, 0x65, 0x78, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x35, 0x0a, 0x14, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x2a, 0x4c, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x66,
	0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x5f, 0x44, 0x49, 0x46, 0x46, 0x49, 0x43, 0x55, 0x4c, 0x54, 0x59, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x45, 0x41, 0x53, 0x59, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x44,
	0x49, 0x55, 0x4d, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x41, 0x52, 0x44, 0x10, 0x03, 0x2a,
	0x46, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x4c, 0x41, 0x4e, 0x47, 0x55, 0x47, 0x41, 0x45, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x59, 0x54, 0x48, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x4a, 0x41, 0x56, 0x41, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4a, 0x41, 0x56, 0x41, 0x53,
	0x43, 0x52, 0x49, 0x50, 0x54, 0x10, 0x03, 0x2a, 0x66, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x00, 0x12, 0x1a, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x12, 0x18,
	0x0a, 0x14, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x43, 0x4f, 0x44, 0x49, 0x4e, 0x47,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x4e, 0x41, 0x55,
	0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x02, 0x42,
	0x09, 0x5a, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_code2gather_proto_rawDescOnce sync.Once
	file_code2gather_proto_rawDescData = file_code2gather_proto_rawDesc
)

func file_code2gather_proto_rawDescGZIP() []byte {
	file_code2gather_proto_rawDescOnce.Do(func() {
		file_code2gather_proto_rawDescData = protoimpl.X.CompressGZIP(file_code2gather_proto_rawDescData)
	})
	return file_code2gather_proto_rawDescData
}

var file_code2gather_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_code2gather_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_code2gather_proto_goTypes = []interface{}{
	(QuestionDifficulty)(0),          // 0: code2gather.QuestionDifficulty
	(Language)(0),                    // 1: code2gather.Language
	(ErrorCode)(0),                   // 2: code2gather.ErrorCode
	(*QuestionMessage)(nil),          // 3: code2gather.QuestionMessage
	(*RoomMessage)(nil),              // 4: code2gather.RoomMessage
	(*CreateRoomRequest)(nil),        // 5: code2gather.CreateRoomRequest
	(*CreateRoomResponse)(nil),       // 6: code2gather.CreateRoomResponse
	(*CreateMeetingRequest)(nil),     // 7: code2gather.CreateMeetingRequest
	(*CreateRatingRequest)(nil),      // 8: code2gather.CreateRatingRequest
	(*ErrorResponse)(nil),            // 9: code2gather.ErrorResponse
	(*ClientRequest)(nil),            // 10: code2gather.ClientRequest
	(*JoinRoomRequest)(nil),          // 11: code2gather.JoinRoomRequest
	(*JoinRoomResponse)(nil),         // 12: code2gather.JoinRoomResponse
	(*ExecuteCodeRequest)(nil),       // 13: code2gather.ExecuteCodeRequest
	(*ExecuteCodeBroadcast)(nil),     // 14: code2gather.ExecuteCodeBroadcast
	(*ExecuteCodeResponse)(nil),      // 15: code2gather.ExecuteCodeResponse
	(*DisconnectBroadcast)(nil),      // 16: code2gather.DisconnectBroadcast
	(*CompleteQuestionRequest)(nil),  // 17: code2gather.CompleteQuestionRequest
	(*CompleteQuestionResponse)(nil), // 18: code2gather.CompleteQuestionResponse
	(*SubmitRatingRequest)(nil),      // 19: code2gather.SubmitRatingRequest
	(*SubmitRatingResponse)(nil),     // 20: code2gather.SubmitRatingResponse
}
var file_code2gather_proto_depIdxs = []int32{
	0,  // 0: code2gather.QuestionMessage.difficulty:type_name -> code2gather.QuestionDifficulty
	0,  // 1: code2gather.CreateRoomRequest.difficulty:type_name -> code2gather.QuestionDifficulty
	0,  // 2: code2gather.CreateMeetingRequest.difficulty:type_name -> code2gather.QuestionDifficulty
	1,  // 3: code2gather.CreateMeetingRequest.language:type_name -> code2gather.Language
	11, // 4: code2gather.ClientRequest.join_room_request:type_name -> code2gather.JoinRoomRequest
	13, // 5: code2gather.ClientRequest.execute_code_request:type_name -> code2gather.ExecuteCodeRequest
	17, // 6: code2gather.ClientRequest.complete_question_request:type_name -> code2gather.CompleteQuestionRequest
	19, // 7: code2gather.ClientRequest.submit_rating_request:type_name -> code2gather.SubmitRatingRequest
	3,  // 8: code2gather.JoinRoomResponse.question:type_name -> code2gather.QuestionMessage
	1,  // 9: code2gather.ExecuteCodeRequest.language:type_name -> code2gather.Language
	1,  // 10: code2gather.CompleteQuestionRequest.language:type_name -> code2gather.Language
	3,  // 11: code2gather.CompleteQuestionResponse.next_question:type_name -> code2gather.QuestionMessage
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_code2gather_proto_init() }
func file_code2gather_proto_init() {
	if File_code2gather_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_code2gather_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMeetingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteCodeBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisconnectBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteQuestionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteQuestionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitRatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code2gather_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitRatingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_code2gather_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*ClientRequest_JoinRoomRequest)(nil),
		(*ClientRequest_ExecuteCodeRequest)(nil),
		(*ClientRequest_CompleteQuestionRequest)(nil),
		(*ClientRequest_SubmitRatingRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_code2gather_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_code2gather_proto_goTypes,
		DependencyIndexes: file_code2gather_proto_depIdxs,
		EnumInfos:         file_code2gather_proto_enumTypes,
		MessageInfos:      file_code2gather_proto_msgTypes,
	}.Build()
	File_code2gather_proto = out.File
	file_code2gather_proto_rawDesc = nil
	file_code2gather_proto_goTypes = nil
	file_code2gather_proto_depIdxs = nil
}
