FROM golang:alpine

ENV GO111MODULE=on

RUN apk add yarn

RUN mkdir -p /home/node/app

WORKDIR /home/node/app/room

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go mod vendor

CMD yarn install && yarn start
