FROM golang:alpine

ENV GO111MODULE=on

RUN mkdir -p /home/node/app

WORKDIR /home/node/app/room

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

CMD go mod vendor && go run ./src/main.go
