FROM node:lts

RUN apt-get update && apt-get install -y jq
RUN mkdir -p /home/node/app

COPY ../tsconfig.base.json /home/node/app/tsconfig.base.json

WORKDIR /home/node/app/history

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY . .

CMD ["yarn", "start"]
