FROM node:14.17-alpine

RUN apk add --no-cache jq
RUN mkdir -p /home/node/app

COPY ../tsconfig.base.json /home/node/app/tsconfig.base.json

WORKDIR /home/node/app/coding

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY . .

CMD ["yarn", "start"]
