FROM python:3.9

RUN curl -sL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py && python - -y --git https://github.com/python-poetry/poetry.git

RUN mkdir -p /home/node/app

WORKDIR /home/node/app/code-executor

COPY . /home/node/app/code-executor/

RUN pip install -r requirements.txt && pip install gunicorn

# RUN ./deploy.sh
EXPOSE 8005

# gunicorn --chdir app main:app -w 2 --threads 2 -b 0.0.0.0:8005
ENTRYPOINT [ "gunicorn", "src.wsgi:app", "-b 0.0.0.0:8005" ]

